// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rexdzphtitpkzkguaata.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJleGR6cGh0aXRwa3prZ3VhYXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTU2ODIsImV4cCI6MjA2NjU3MTY4Mn0.GN1gPZol2sgo7_W5mw8IyjesQRErPHK7ezgOidWaspo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});